### ISSUE TITLE
rTGS DB error

### ISSUE THREAD

**Issue by IrfanMeo** [kaleemullah360/rTGS#2]
at this address http://localhost:3000/coap DB output is
1166    275 480  1   1   1   STANDING   CoAP_undefinedSec_undefinedHop  38  2016-06-17 20:18:33

While at http://localhost:3000/get-coap DB output is correct
1159    268 440  1   1   1   STANDING   CoAP_1Sec_1Hop  39  2016-06-17 20:17:54

**Comment by kaleemullah360** [comment]
Issue Resolved, make test....
