### ISSUE TITLE
CoAP rTGS hang problem

### ISSUE THREAD

**Issue by IrfanMeo** [kaleemullah360/rTGS#3]
CoAP starts retransmission in Cupper plugin and hang in rTGS

**Comment by IrfanMeo** [comment]
CoAP: Ping failed, Device is not reachable, Trying again ...

**Comment by kaleemullah360** [comment]
in that case do ping in terminal to make sure that mote is reachable.
`ping6 aaaa::c30c:0:0:2`

**Comment by IrfanMeo** [comment]
irfan@irfan-Inspiron-N5050:~/kontiki/examples/ipv6/rpl-border-router$ ping6 aaaa::c30c:0:0:2
PING aaaa::c30c:0:0:2(aaaa::c30c:0:0:2) 56 data bytes
^C
--- aaaa::c30c:0:0:2 ping statistics ---
24 packets transmitted, 0 received, 100% packet loss, time 23183ms

**Comment by kaleemullah360** [comment]
this means no connectivity.
try `ping6 aaaa::c30c:0:0:1`

**Comment by IrfanMeo** [comment]
irfan@irfan-Inspiron-N5050:~/kontiki/examples/ipv6/rpl-border-router$ ping6 aaaa::c30c:0:0:1
PING aaaa::c30c:0:0:1(aaaa::c30c:0:0:1) 56 data bytes
64 bytes from aaaa::c30c:0:0:1: icmp_seq=1 ttl=64 time=19.7 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=2 ttl=64 time=20.1 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=3 ttl=64 time=20.0 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=4 ttl=64 time=20.1 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=5 ttl=64 time=20.0 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=6 ttl=64 time=20.0 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=7 ttl=64 time=19.9 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=8 ttl=64 time=20.1 ms
64 bytes from aaaa::c30c:0:0:1: icmp_seq=9 ttl=64 time=20.0 ms
^C
--- aaaa::c30c:0:0:1 ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 8010ms
rtt min/avg/max/mdev = 19.779/20.053/20.198/0.224 ms

**Comment by kaleemullah360** [comment]
put the coap mote near the border router, then ping it.
