### ISSUE TITLE
CoAP Mote Hang

### ISSUE THREAD

**Issue by IrfanMeo** [kaleemullah360/rTGS#5]
Mote with CoAP Protocol traffic hangs after too much shuffling.?

**Comment by kaleemullah360** [comment]
### **Congestion Control for CoAP:**

> Because UDP itself provides no congestion control mechanisms, it is up to the applications and    application-layer protocols that use UDP for Internet communication to employ suitable mechanisms to prevent congestion collapse an establish a degree of fairness. CoAP is one such application-layer protocol.

[RFC2914] identifies two major reasons why congestion control mechanisms are critical for the stable operation of the Internet:
1.  The prevention of congestion collapse, i.e., a state where an
      increase in network load results in a decrease in useful work
      done by the network.
2.  The establishment of a degree of fairness, i.e., allowing
      multiple flows to share the capacity of a path reasonably
      equitably.

>    Bulk transfers cause the overwhelming majority of the bytes on the
>    Internet, and the traditional congestion control mechanisms used for
>    bulk transfers are engineered to saturate the network without driving
>    it into congestive collapse.  Fairness between flows is an important
>    secondary consideration when the network operates around the
>    saturation point, so that new flows are not disadvantaged compared to
>    established flows, and can obtain a reasonable share of the capacity
>    quickly.

[https://tools.ietf.org/html/draft-eggert-core-congestion-control-01](https://tools.ietf.org/html/draft-eggert-core-congestion-control-01)

**Comment by kaleemullah360** [comment]
can you count after how many times shuffling it stop responding ?
and after how many seconds it becomes not responding.

because CoAP RTO (Re-transmission Time Out ) is three.
